name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# https://github.com/cypress-io/github-action#start-server
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
          uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            start: npm start
